'use strict';

/**
 * Creates or repairs backend/.env.
 *
 * Run with `npm run env:init`. It preserves anything already configured and
 * only fills in what is missing — in particular it replaces the placeholder
 * JWT secrets that ship in the source code with freshly generated 48-byte
 * random values, because a signing key that appears in the repository means
 * anyone can forge a token for any account.
 *
 * Secrets are never printed to the console.
 *
 *   node scripts/init-env.js            # fill in anything missing
 *   node scripts/init-env.js --force    # regenerate the secrets as well
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env');
const FORCE = process.argv.includes('--force');

const PLACEHOLDERS = new Set([
  'your-super-secret-key-min-32-chars-long',
  'your-secret-key',
  'secret',
  'changeme',
  'change-me',
  'test',
  'development',
  'password',
  '',
]);

/**
 * The keys this script owns and rewrites.
 *
 * Anything else found in an existing .env is preserved and re-appended at the
 * end. That matters more than it looks: the first version regenerated the file
 * from this template alone, so every key the template had not been taught about
 * was silently deleted. It would have done exactly that to the mobile money
 * credentials when they were added — the operator would have pasted in a
 * provider's API key, run the documented setup command, and watched it vanish
 * with no error and no diff to read.
 */
const MANAGED = new Set([
  'NODE_ENV',
  'PORT',
  'MONGODB_URI',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'JWT_ACCESS_TTL',
  'JWT_REFRESH_TTL_DAYS',
  'PUBLIC_BASE_URL',
  'CORS_ORIGINS',
  'RESEND_API_KEY',
  'EMAIL_FROM',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'ORANGE_MONEY_BASE_URL',
  'ORANGE_MONEY_MERCHANT_ID',
  'ORANGE_MONEY_API_KEY',
  'ORANGE_MONEY_CALLBACK_SECRET',
  'ORANGE_MONEY_CURRENCY',
  'LONESTAR_MOMO_BASE_URL',
  'LONESTAR_MOMO_MERCHANT_ID',
  'LONESTAR_MOMO_API_KEY',
  'LONESTAR_MOMO_CALLBACK_SECRET',
  'LONESTAR_MOMO_CURRENCY',
  'LOG_LEVEL',
]);

/** Parse an existing .env into a plain map, ignoring comments. */
function readExisting() {
  const values = new Map();

  if (!fs.existsSync(ENV_PATH)) return values;

  for (const line of fs.readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (match) values.set(match[1], match[2].trim());
  }

  return values;
}

const existing = readExisting();
const generated = [];
const kept = [];

const strongSecret = () => crypto.randomBytes(48).toString('base64url');

/**
 * Keep an existing value unless it is missing, a known placeholder, or too
 * short to be a real secret.
 */
function resolveSecret(name) {
  const current = existing.get(name);
  const usable = current && current.length >= 32 && !PLACEHOLDERS.has(current);

  if (usable && !FORCE) {
    kept.push(name);
    return current;
  }

  generated.push(name);
  return strongSecret();
}

function resolveValue(name, fallback) {
  const current = existing.get(name);
  if (current && !PLACEHOLDERS.has(current)) {
    kept.push(name);
    return current;
  }
  return fallback;
}

const accessSecret = resolveSecret('JWT_ACCESS_SECRET');
const refreshSecret = resolveSecret('JWT_REFRESH_SECRET');

if (accessSecret === refreshSecret) {
  process.stderr.write('Refusing to write: the access and refresh secrets must differ.\n');
  process.exit(1);
}

const port = resolveValue('PORT', '5000');
const mongoUri = existing.get('MONGODB_URI') || '';

/**
 * Everything the template below does not mention, kept verbatim.
 *
 * A key that was already in the file was put there deliberately — a provider
 * credential, an override someone needed — and this script has no way to know it
 * is disposable, so it does not dispose of it.
 */
const unmanaged = [...existing.entries()].filter(([key]) => !MANAGED.has(key));

const preserved = unmanaged.length
  ? `\n# Preserved from the previous file. This script does not manage these.\n${unmanaged
      .map(([key, value]) => `${key}=${value}`)
      .join('\n')}\n`
  : '';

const contents = `# Wuteve Global Academy — local configuration.
# Generated by scripts/init-env.js. This file is gitignored; never commit it.

NODE_ENV=${resolveValue('NODE_ENV', 'development')}
PORT=${port}

MONGODB_URI=${mongoUri}

# Generated locally. Use DIFFERENT values on the server: a secret that has
# existed on a developer machine should not sign production sessions.
JWT_ACCESS_SECRET=${accessSecret}
JWT_REFRESH_SECRET=${refreshSecret}
JWT_ACCESS_TTL=${resolveValue('JWT_ACCESS_TTL', '15m')}
JWT_REFRESH_TTL_DAYS=${resolveValue('JWT_REFRESH_TTL_DAYS', '30')}

PUBLIC_BASE_URL=${resolveValue('PUBLIC_BASE_URL', `http://localhost:${port}`)}
CORS_ORIGINS=${existing.get('CORS_ORIGINS') || ''}

RESEND_API_KEY=${existing.get('RESEND_API_KEY') || ''}
EMAIL_FROM=${existing.get('EMAIL_FROM') || 'Wuteve Global Academy <onboarding@resend.dev>'}

STRIPE_SECRET_KEY=${existing.get('STRIPE_SECRET_KEY') || ''}
STRIPE_WEBHOOK_SECRET=${existing.get('STRIPE_WEBHOOK_SECRET') || ''}

# Mobile money. A method becomes selectable once all four of its values are set —
# but selectable is not payable: the charge calls are not implemented yet.
# See docs/PAYMENTS.md.
ORANGE_MONEY_BASE_URL=${existing.get('ORANGE_MONEY_BASE_URL') || ''}
ORANGE_MONEY_MERCHANT_ID=${existing.get('ORANGE_MONEY_MERCHANT_ID') || ''}
ORANGE_MONEY_API_KEY=${existing.get('ORANGE_MONEY_API_KEY') || ''}
ORANGE_MONEY_CALLBACK_SECRET=${existing.get('ORANGE_MONEY_CALLBACK_SECRET') || ''}
ORANGE_MONEY_CURRENCY=${existing.get('ORANGE_MONEY_CURRENCY') || 'lrd'}

LONESTAR_MOMO_BASE_URL=${existing.get('LONESTAR_MOMO_BASE_URL') || ''}
LONESTAR_MOMO_MERCHANT_ID=${existing.get('LONESTAR_MOMO_MERCHANT_ID') || ''}
LONESTAR_MOMO_API_KEY=${existing.get('LONESTAR_MOMO_API_KEY') || ''}
LONESTAR_MOMO_CALLBACK_SECRET=${existing.get('LONESTAR_MOMO_CALLBACK_SECRET') || ''}
LONESTAR_MOMO_CURRENCY=${existing.get('LONESTAR_MOMO_CURRENCY') || 'lrd'}

LOG_LEVEL=${resolveValue('LOG_LEVEL', 'debug')}
${preserved}`;

fs.writeFileSync(ENV_PATH, contents, { encoding: 'utf8', mode: 0o600 });

process.stdout.write(`\nWrote ${path.relative(process.cwd(), ENV_PATH)}\n\n`);
if (generated.length > 0) process.stdout.write(`  Generated new random secrets: ${generated.join(', ')}\n`);
if (kept.length > 0) process.stdout.write(`  Kept existing values: ${kept.join(', ')}\n`);
if (unmanaged.length > 0) {
  process.stdout.write(`  Preserved untouched: ${unmanaged.map(([key]) => key).join(', ')}\n`);
}

if (!mongoUri) {
  process.stdout.write(
    '\n  MONGODB_URI is empty — set it before starting:\n' +
      '    local server:  mongodb://127.0.0.1:27017/wuteve\n' +
      '    MongoDB Atlas: mongodb+srv://<user>:<password>@<cluster>/wuteve\n'
  );
}

process.stdout.write('\n');
