'use strict';

/**
 * Creates or repairs backend/.env.
 *
 * Run with `npm run env:init`. It preserves anything already configured and
 * only fills in what is missing — in particular it replaces the placeholder
 * JWT secrets that ship in the source code with freshly generated 48-byte
 * random values, because a signing key that appears in the repository means
 * anyone can forge a token for any account.
 *
 * Secrets are never printed to the console.
 *
 *   node scripts/init-env.js            # fill in anything missing
 *   node scripts/init-env.js --force    # regenerate the secrets as well
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env');
const FORCE = process.argv.includes('--force');

const PLACEHOLDERS = new Set([
  'your-super-secret-key-min-32-chars-long',
  'your-secret-key',
  'secret',
  'changeme',
  'change-me',
  '',
]);

/** Parse an existing .env into a plain map, ignoring comments. */
function readExisting() {
  const values = new Map();

  if (!fs.existsSync(ENV_PATH)) return values;

  for (const line of fs.readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (match) values.set(match[1], match[2].trim());
  }

  return values;
}

const existing = readExisting();
const generated = [];
const kept = [];

const strongSecret = () => crypto.randomBytes(48).toString('base64url');

/**
 * Keep an existing value unless it is missing, a known placeholder, or too
 * short to be a real secret.
 */
function resolveSecret(name) {
  const current = existing.get(name);
  const usable = current && current.length >= 32 && !PLACEHOLDERS.has(current);

  if (usable && !FORCE) {
    kept.push(name);
    return current;
  }

  generated.push(name);
  return strongSecret();
}

function resolveValue(name, fallback) {
  const current = existing.get(name);
  if (current && !PLACEHOLDERS.has(current)) {
    kept.push(name);
    return current;
  }
  return fallback;
}

const accessSecret = resolveSecret('JWT_ACCESS_SECRET');
const refreshSecret = resolveSecret('JWT_REFRESH_SECRET');

if (accessSecret === refreshSecret) {
  process.stderr.write('Refusing to write: the access and refresh secrets must differ.\n');
  process.exit(1);
}

const port = resolveValue('PORT', '5000');
const mongoUri = existing.get('MONGODB_URI') || '';

const contents = `# Wuteve Global Academy — local configuration.
# Generated by scripts/init-env.js. This file is gitignored; never commit it.

NODE_ENV=${resolveValue('NODE_ENV', 'development')}
PORT=${port}

MONGODB_URI=${mongoUri}

# Generated locally. Use DIFFERENT values on the server: a secret that has
# existed on a developer machine should not sign production sessions.
JWT_ACCESS_SECRET=${accessSecret}
JWT_REFRESH_SECRET=${refreshSecret}
JWT_ACCESS_TTL=${resolveValue('JWT_ACCESS_TTL', '15m')}
JWT_REFRESH_TTL_DAYS=${resolveValue('JWT_REFRESH_TTL_DAYS', '30')}

PUBLIC_BASE_URL=${resolveValue('PUBLIC_BASE_URL', `http://localhost:${port}`)}
CORS_ORIGINS=${existing.get('CORS_ORIGINS') || ''}

RESEND_API_KEY=${existing.get('RESEND_API_KEY') || ''}
EMAIL_FROM=${existing.get('EMAIL_FROM') || 'Wuteve Global Academy <onboarding@resend.dev>'}

STRIPE_SECRET_KEY=${existing.get('STRIPE_SECRET_KEY') || ''}
STRIPE_WEBHOOK_SECRET=${existing.get('STRIPE_WEBHOOK_SECRET') || ''}

LOG_LEVEL=${resolveValue('LOG_LEVEL', 'debug')}
`;

fs.writeFileSync(ENV_PATH, contents, { encoding: 'utf8', mode: 0o600 });

process.stdout.write(`\nWrote ${path.relative(process.cwd(), ENV_PATH)}\n\n`);
if (generated.length > 0) process.stdout.write(`  Generated new random secrets: ${generated.join(', ')}\n`);
if (kept.length > 0) process.stdout.write(`  Kept existing values: ${kept.join(', ')}\n`);

if (!mongoUri) {
  process.stdout.write(
    '\n  MONGODB_URI is empty — set it before starting:\n' +
      '    local server:  mongodb://127.0.0.1:27017/wuteve\n' +
      '    MongoDB Atlas: mongodb+srv://<user>:<password>@<cluster>/wuteve\n'
  );
}

process.stdout.write('\n');
